_commit: b7f2804
_src_path: gh:monarch-initiative/koza-ingest-template
copyright_year: '2025'
email: info@monarchinitiative.org
full_name: Monarch Initiative
github_handle: monarch-initiative
github_org: monarch-initiative
license: BSD-3-Clause
project_description: Monarch Initiative data ingest for MMRRC (Mutant Mouse Resource
    & Research Centers) - capturing allele to genotype associations, genotype nodes,
    and genotype to phenotype associations
project_name: mmrrc-ingest
project_slug: mmrrc-ingest
