# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 69ebe05
_src_path: gh:monarch-initiative/cookiecutter-monarch-ingest
copyright_year: '2025'
email: info@monarchinitiative.org
full_name: Monarch Initiative
gh_action_docs_preview: true
github_handle: monarch-initiative
github_org: monarch-initiative
ingest_source: mmrrc
ingest_type: associations
license: BSD-3-Clause
min_python_version: '3.10'
project_description: Monarch Initiative data ingest for MMRRC (Mutant Mouse Resource
    & Research Centers) - capturing allele to genotype associations, genotype nodes,
    and genotype to phenotype associations
project_name: MMRRC Ingest
project_slug: mmrrc-ingest
